version: '3.8'

services:

  web:
    container_name: backend-portafolio
    build: 
    build:
      context: ./project
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://4dm1nport:4cc3s0gr4nt3d@db:5432/devdb
    depends_on:
      - db

  db:
    container_name: db-portafolio
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=4dm1nport
      - POSTGRES_PASSWORD=4cc3s0gr4nt3d
      - POSTGRES_DB=devdb
