"""init

Revision ID: c0d9dd096c74
Revises: 
Create Date: 2021-10-05 20:14:49.060404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c0d9dd096c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('award', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('learning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tech', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_award'), 'project', ['award'], unique=False)
    op.create_index(op.f('ix_project_category'), 'project', ['category'], unique=False)
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_image'), 'project', ['image'], unique=False)
    op.create_index(op.f('ix_project_images'), 'project', ['images'], unique=False)
    op.create_index(op.f('ix_project_learning'), 'project', ['learning'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_published'), 'project', ['published'], unique=False)
    op.create_index(op.f('ix_project_summary'), 'project', ['summary'], unique=False)
    op.create_index(op.f('ix_project_tech'), 'project', ['tech'], unique=False)
    op.create_index(op.f('ix_project_tools'), 'project', ['tools'], unique=False)
    op.create_index(op.f('ix_project_updated_at'), 'project', ['updated_at'], unique=False)
    op.create_index(op.f('ix_project_url'), 'project', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_url'), table_name='project')
    op.drop_index(op.f('ix_project_updated_at'), table_name='project')
    op.drop_index(op.f('ix_project_tools'), table_name='project')
    op.drop_index(op.f('ix_project_tech'), table_name='project')
    op.drop_index(op.f('ix_project_summary'), table_name='project')
    op.drop_index(op.f('ix_project_published'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_learning'), table_name='project')
    op.drop_index(op.f('ix_project_images'), table_name='project')
    op.drop_index(op.f('ix_project_image'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_index(op.f('ix_project_category'), table_name='project')
    op.drop_index(op.f('ix_project_award'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
